export const dataSource = [
  {
    key: 1,
    taskId: "TT-001",
    taskname: "Task name1",
    project: "Java Team",
    priority: "High",
    company: "Company 1",
    taskdescription: "Desc 1",
    createdOn: "22/11/2020",
    completedOn: "",
    taskMode: "Todo",
  },
  {
    key: 2,
    taskId: "TT-002",
    taskname: "Task name2",
    project: "Python Team",
    priority: "Low",
    company: "Company 2",
    taskdescription: "Desc 2",
    createdOn: "23/11/2017",
    completedOn: "",
    taskMode: "Todo",
  },
  {
    key: 3,
    taskId: "TT-003",
    taskname: "Task name3",
    project: "Devops Team",
    priority: "Medium",
    company: "Company 3",
    taskdescription: "Desc 3",
    createdOn: "20/12/2020",
    completedOn: "",
    taskMode: "Todo",
  },
  {
    key: 4,
    taskId: "TT-004",
    taskname: "Task name4",
    project: "Java Team",
    priority: "High",
    company: "Company 4",
    taskdescription: "Desc 4",
    createdOn: "12/01/2008",
    completedOn: "",
    taskMode: "InProgress",
  },
  {
    key: 5,
    taskId: "TT-005",
    taskname: "Task name5",
    project: "Python Team",
    priority: "Low",
    company: "Company 5",
    taskdescription: "Desc 5",
    createdOn: "10/05/2015",
    completedOn: "",
    taskMode: "InProgress",
  },
  {
    key: 6,
    taskId: "TT-006",
    taskname: "Task name6",
    project: "Devops Team",
    priority: "Medium",
    company: "Company 6",
    taskdescription: "Desc 6",
    createdOn: "18/09/2018",
    completedOn: "",
    taskMode: "InProgress",
  },
  {
    key: 7,
    taskId: "TT-007",
    taskname: "Task name7",
    project: "Python Team",
    priority: "Low",
    company: "Company 7",
    taskdescription: "Desc 7",
    createdOn: "22/11/2020",
    completedOn: "14/01/2021",
    taskMode: "Done",
  },
  {
    key: 8,
    taskId: "TT-008",
    taskname: "Task name8",
    project: "Devops Team",
    priority: "Medium",
    company: "Company 8",
    taskdescription: "Desc 8",
    createdOn: "05/02/2021",
    completedOn: "13/02/2021",
    taskMode: "Done",
  },
];
